### ISSUE TITLE
Question about Synchronization of DVL, IMU, and Barometer

### ISSUE THREAD

**Issue by Liuxiaoyan-sdu** [umfieldrobotics/TURTLMap#1]
Hello,

I am reading your paper titled "TURTLMap: Real-time Localization and Dense Mapping of Low-texture Underwater Environments with a Low-cost Unmanned Underwater Vehicle". In the paper, you mention that synchronization between sensors like the DVL, IMU, and barometer is crucial for accurate localization. I would like to learn more about the following:

How do you handle the time synchronization between the DVL and other sensors (such as the IMU and barometer) in TURTLMap?
Are there any tools or methods (such as ROS’s time synchronization features) that you use to ensure the sensors are properly synchronized?
If there are any more detailed explanations of the synchronization mechanism or code snippets that I could refer to, could you kindly provide some guidance or links?
Thank you very much for your help!
![屏幕截图 2024-09-10 190928](https://github.com/user-attachments/assets/2d8d0442-ce7d-4fb5-93e8-fd939d84afd6)

**Comment by Song-Jingyu** [comment]
Hi Xiaoyan,

Thanks for your interest in this work. Yes sensor synchronization is important, and it is very important in ensuring this is correctly handled. Please refer to this figure to see how we handle this. Basically, we compensate the DVL measurements to sync with the barometer measurements, which is validated in Table III in the paper (pseudo velocity). Also, you can watch this [video](https://youtu.be/ensndBa2L9g?si=5UJAxYO2ojvjeoLx&t=2140) to for more details.

<img width="946" alt="image" src="https://github.com/user-attachments/assets/be791dd3-c6c5-489e-ae96-46f66bfa4d9c">

**Comment by Liuxiaoyan-sdu** [comment]
Thank you for your time and response earlier. I realize my initial query might not have fully conveyed the specificity of my concern. I am particularly interested in understanding how the synchronization of sensor data timestamps is handled in the TURTLMap system, especially in scenarios where there is no hardware synchronization between sensors like the DVL and the depth gauge.

To be more specific:

How is the timestamp alignment achieved for each sensor’s data to ensure that readings from different sensors (e.g., DVL and depth gauge) are consistent and accurately correlated in time, especially when these sensors do not have built-in hardware synchronization?

**Comment by Song-Jingyu** [comment]
Thanks!
Since IMU is fast (250Hz in our case), it can be directly considered as always timesynced with other sensors.
We add keyframe based on barometer measurements. So the only thing is to consider is syncing DVL with barometer.
We cannot control DVL's frequency as it depends on the distance to the bottom. Therefore, we propose a mechanism to propagate a pseudo DVL measurements so it is synced with the barometer measurement. We use the IMU measurements within (last DVL measurement, current barometer measurement) to propagate the pseudo measurement.
Hope this information helps.
