### ISSUE TITLE
Question regarding ground truth data

### ISSUE THREAD

**Issue by gsai29** [umfieldrobotics/TURTLMap#2]
Hello, 

I have read the paper TURTLMap. Thank you for providing the TURTLMap dataset and open-sourcing your work. It would be of great help to me, for focusing my work on underwater sensor fusion . 

In the Data Preparation preparation, it is stated that the ground truth is added in the logs in txt format. However, I only found the sensor data rosbags in the drive link. 

Could you please let me know if the ground truth data is available for download or if I'm missing something? 

Thanks

**Comment by Song-Jingyu** [comment]
Hi,

Thank you for your interest in TURTLMap. We forgot to also upload the txt file for ground truth poses from MoCap. I have uploaded the GT logs in the Google Drive link. I have updated the docs of the repository and hope the update will solve your issues.

Thank you
Jingyu
