### ISSUE TITLE
Question regarding the calibration of the ZED stereo camera

### ISSUE THREAD

**Issue by ShenYuan-sean** [umfieldrobotics/TURTLMap#3]
Hello,

Thank you for providing the TURTLMap dataset and open-sourcing your work！
I have a question regarding the calibration of the ZED stereo camera for underwater applications. Specifically, can the extrinsics between the left and right cameras be calibrated on land, or do both the intrinsics and extrinsics need to be calibrated underwater due to the effects of refraction?

Thank you!

**Comment by Song-Jingyu** [comment]
Thanks for your question! This is a great question. We actually recommend calibrating the extrinsics (i.e., transformation between L/R cameras, transformation between camera and IMU if they won't change when placed in the enclosure) on land. The image quality will be better, and it will be easier to move either the sensor rig or the calibration target for better distribution on calibration samples.
