### ISSUE TITLE
Benchmarking against visual inertial solutions.

### ISSUE THREAD

**Issue by khshmt** [umfieldrobotics/TURTLMap#4]
Thank you for open-sourcing your work and dataset! It's a valuable resource for the community.

I'm interested in evaluating the estimated trajectory from TURTLMap against a visual-inertial solution like ORB-SLAM3. However, the dataset currently only includes point cloud data.

To be able to compare the results, I would need the corresponding image data as well. Would it be possible to provide the image data associated with the point cloud sequences?

If sharing the original images isn't feasible, perhaps you could suggest alternative approaches.

Thank you for your time and consideration

**Comment by onurbagoren** [comment]
Hi!

Thanks for reaching out about this. The images should already be in the rosbags we provided in the [Data Preparation](https://github.com/umfieldrobotics/TURTLMap/blob/main/docs/data_preparation.md) page. If you go to the google drive links we provided for [log1](https://drive.google.com/drive/folders/1WLPOTmcomejHVN03Qs8s_scjXoCne35e) or [log2](https://drive.google.com/drive/folders/1WNZGHc0heD0MtYR1I4XDXcoKkpWlZDqO), the bags that end with `zed` should have `CompressedImage` types that you can use in benchmarking any visual-inertial algorithm.

Keep in mind that there are multiple bags on google drive, another one being the one with the IMU data in it. You'll want to play them together as described in [Getting Started](https://github.com/umfieldrobotics/TURTLMap/blob/main/docs/getting_started_turtlmap.md). Feel free to use the specific command on [line 10](https://github.com/umfieldrobotics/TURTLMap/blob/8f5ee703eca927dca911967aab0b83c5fa30a4ed/launch/turtlmap.launch#L10) of `launch/turtlmap.launch` for getting the images and the IMU synchronized to later use for ORB-SLAM.

Let us know if you have any further questions!
